### ISSUE TITLE
Playstation 2 support via OPL

### ISSUE THREAD

**Issue by Invictaz** [jhonathanc/ps3netsrv-android#1]
Is it possible to build a Playstation 2 Net Serv app for Open PS2 Loader? In that case we can Connect a small Android device via UTP to our Playstation 2 and load the ISO files in that way.

Or via uLaunchElf

**Comment by aldostools** [comment]
I haven't used Open PS2 Loader, but I think it supports SMB shares. If that's the case, then you could use one of the SMB/LAN servers APK for Android.

ps3netsrv uses a proprietary protocol developed by Cobra Team. Until now, there wasn't any APK able to host ISOs for PS3 on Android.

**Comment by jhonathanc** [comment]
Changed the label to invalid feature request, since PS2 OPL Supports SMB protocol and there is some SMB Apps for Android.

**Comment by Invictaz** [comment]
@jhonathanc please name the appstore you are suggesting. Most of thema are fake servers on the Google Play store so your statement as false is incorrect.

**Comment by aldostools** [comment]
@Invictaz your request is still invalid due the reasons that I commented.

You can try some of SMB apps in Google Play. 
https://play.google.com/store/search?q=smb&c=apps

I know X-plore File Manager is a very good app, although I don't know if it compatible with OPL.

**Comment by jhonathanc** [comment]
@aldostools, do you remember if there is some especial treatment for PS2 discs on ps3netsrv, on both sides, client and server? If not, maybe we can try to ask to OPL devs to implement the "Cobra Net Server" protocol on OPL.

**Comment by jhonathanc** [comment]
> PS2 games emulated on PS3 only work from /dev_hdd0.
> 
> Games mounted from any other sources, should be copied first to /dev_hdd0 to play them.

But the data are accessed the same way? using read file command and read file critical command?

**Comment by aldostools** [comment]
I think OPL is only useful on B/C consoles. Non-B/C consoles rely on ps2_netemu that only can emulate from /dev_hdd0

PS3 with B/C can play them from disc & USB, but I don't know how OPL handles remote ISO on these consoles.

**Comment by jhonathanc** [comment]
> I think OPL is only useful on B/C consoles. Non-B/C consoles rely on ps2_netemu that only can emulate from /dev_hdd0
> 
> PS3 with B/C can play them from disc & USB, but I don't know how OPL handles remote ISO on these consoles.

I think the OP is trying to use on a real PS2, not a PS3. If the data on server are acessed the same way, for different kinds of iso (PS1, PS2, PS3), the OPL could implement the client side it with some effort... But if there is a different handling, of course it will not work and would require more time and development...

**Comment by aldostools** [comment]
ps3netsrv is for PS3... to add support in OPL, it would have to implement:

1- A way to scan & mount games using ps3netsrv protocol
2- Implement a proxy service like netiso.sprx that handle the communication between the SCSI driver and the remote server.

**Comment by jhonathanc** [comment]
I just checked the OPL source and it appears to not be difficult. I'll try to create a "new device", like the "device-smb", to implement the basics of the Cobra Net Protocol:

https://github.com/ps2homebrew/Open-PS2-Loader/blob/6a5be80ef27e90347f3245301531b0ae9a4b3864/modules/iopcore/cdvdman/device-smb.c
