### ISSUE TITLE
[BUG] Random Crash 

### ISSUE THREAD

**Issue by VinnyRadev** [jhonathanc/ps3netsrv-android#17]
Randomly when starting a game the PS corrupt.
![IMG_20230516_012130](https://github.com/jhonathanc/ps3netsrv-android/assets/61891369/0818d609-5fb0-4139-bc75-9b84ea70e217)

a simple restart fix it until next time.

**Comment by jhonathanc** [comment]
I'll try one more thing, keep both ParcelFileDescriptor, FileInputStream and FileChannel during the life cycle of object CustomDocumentFile. I think it will solve the I/O bottleneck the application has with SAF (I think this is the cause of random freezes).

**Comment by aldostools** [comment]
On [Lollipop](https://github.com/jhonathanc/ps3netsrv-android/blob/main/app/src/main/java/com/jhonju/ps3netsrv/server/io/RandomAccessFileLollipop.java) you open/close the file for each read operation. This has a big overhead on performance.

I'm not sure if it's related to this issue, but maybe keeping the objects pfd, fis & fileChannel cached in memory could help.

**Comment by jhonathanc** [comment]
Understood, but I'm afraid it could lead to the same problem solved on this commit:

https://github.com/jhonathanc/ps3netsrv-android/commit/54c4be7768b449f10015330cf881dbf5a050f7b1

The main difference is I'll keep all necessary pointers in memory to avoid the GC to collect them. I'll create a new branch to let me merge this and check if the performance increased.

**Comment by jhonathanc** [comment]
@VinnyRadev, could you please test this?

https://github.com/jhonathanc/ps3netsrv-android/suites/12932337059/artifacts/698689215

**Comment by VinnyRadev** [comment]
on the first try to start a game it did corrupt it.

**Comment by VinnyRadev** [comment]
on second start same game without refresh of xml and games ,it did load flawlessly

**Comment by jhonathanc** [comment]
Is there any game that this issue is more noticeable?

**Comment by aldostools** [comment]
@jhonathanc wouldn't be safer to use a *try* block when you create the fis object and when you read the file? 
The new code doesn't handle exceptions with the cached objects ;-)

**Comment by jhonathanc** [comment]
> @jhonathanc wouldn't be safer to use a _try_ block when you create the fis object and when you read the file? The new code doesn't handle exceptions with the cached objects ;-)

On constructor, maybe... But on method "read", the exceptions are handled by the Commands, for example:

https://github.com/jhonathanc/ps3netsrv-android/blob/a9dacee908e26701423100e25cca77f695172420/app/src/main/java/com/jhonju/ps3netsrv/server/commands/ReadFileCommand.java#LL47C1-L56C10

**Comment by aldostools** [comment]
Ok. I asked, because the previous code used a *try* block. But if it considered in your logic, then it's fine.

**Comment by VinnyRadev** [comment]
after more tests to reproduce it,it did happen with local hdd game. I'll close it as it may not be the apk at all.
