### ISSUE TITLE
Test en PS3

### ISSUE THREAD

**Issue by TheWizWikii** [jhonathanc/ps3netsrv-android#2]
Hello,

I have tried an ISO and I can't get it to work or it never detects it. I have enabled the netserv with the ip and the port in webman obviously. What kind of iso is functional? In which folders or paths should the game be put. Thanks

**Comment by aldostools** [comment]
The ISO files should be placed in specific folders, depending the type. The folder names are:

PS3ISO
PSXISO
PSPISO
BDISO
DVDISO

GAMES if for PS3 games extracted from ISO or physical disc in folder format,

PS3ISO requires to be created with a tool like IRISMAN, multiMAN, getPS3ISO or PS3 ISO Tools by Rudi Rastelli

**Comment by TheWizWikii** [comment]
Thanks aldo, 

I have the PS3ISO folder with an iso converted with your genps3iso_v2.0 application. The problem is that when I activate the server from the Android device: android / PS3ISO / monopoly.iso it never detects it and the game does not appear in webMAN. I have enabled the scanning of games by LAN NETSERV with the IP and Port indicated by the smartphone

**Comment by aldostools** [comment]
Try mounting the game manually from the web browser using http://ip-address-of-ps3/net0

It should list the folders PS3ISO, etc. Then you enter to PS3ISO and it should show monopoly.iso.
Click on the file size column to mount the game.

Also make sure that You have configured and enabled the IP address of your Android device in /setup.ps3

**Comment by jhonathanc** [comment]
Make sure you are running it over wifi.

**Comment by aldostools** [comment]
@jhonathanc Is it possible to disable the access to mobile network in the application profile?

I had to do it manually to prevent accidental mobile data consumption if the network switches automatically (WiFi+).

If it is not possible, it would be a great addition to show a one time popup to remind the user to do it manually.

**Comment by jhonathanc** [comment]
It's possible, I'll add to a todo list.

**Comment by TheWizWikii** [comment]
> Try mounting the game manually from the web browser using http://ip-address-of-ps3/net0
> 
> It should list the folders PS3ISO, etc. Then you enter to PS3ISO and it should show monopoly.iso.
> Click on the file size column to mount the game.
> 
> Also make sure that You have configured and enabled the IP address of your Android device in /setup.ps3
> 
> Once the game is mounted, the Bluray disc icon should appear on the Game column of XMB.
> You can launch the game clicking on the disc icon or clicking on the game image displayed on the web browser.
> 
> If it doesn't work, you could check if your router is allowing access to the port 38008

From the browser I can enter the folders of the android device but now it does not show the iso. Some suggestions

**Comment by aldostools** [comment]
Did you verify that the ISO image is in the folder PS3ISO in the Folder path specified in Settings of the Android app?

@jhonathanc Do you have any suggestion?

**Comment by jhonathanc** [comment]
Is the device "awaken"? I have to change the code to make it work it as a service and avoid the app to stops when the device "sleeps". But I didn't have the chance to change this yet because I'm helping Zar with an IRD website and API to Managunz consume.

**Comment by TheWizWikii** [comment]
> Did you verify that the ISO image is in the folder PS3ISO in the Folder path specified in Settings of the Android app?
> 
> @jhonathanc Do you have any suggestion?

Of course there are the iso in the PS3ISO folder on my smartphone. I have also verified the routes from the app, changed the port in webman and the app testing 8080 for example and nothing. Everything is going well but it doesn't show the games

Best regards!

**Comment by jhonathanc** [comment]
@TheWizWikii , sorry for the long waiting...

Could you please check if this version works for you?

https://github.com/jhonathanc/ps3netsrv-android/suites/11722209785/artifacts/610186648

**Comment by jhonathanc** [comment]
Closing this issue as it appears to be the same as #12
